/** PawVora product catalog data */
import type { Product } from '../types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'ProBite Salmon Kibble',
    brand: 'PawVora',
    price: 45.99,
    rating: 5.0,
    reviewCount: 342,
    petCategory: 'dogs',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&auto=format&fit=crop&q=80',
    badges: ['Grain-Free', 'Vet Recommended'],
    description: 'Wild-caught Alaskan salmon, cold-pressed to preserve Omega-3s.',
    isBestSeller: true,
  },
  {
    id: 'p2',
    name: 'Whisker Feast Pâté',
    brand: 'PawVora',
    price: 2.50,
    rating: 4.9,
    reviewCount: 218,
    petCategory: 'cats',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=600&auto=format&fit=crop&q=80',
    badges: ['100% Natural', 'No Fillers'],
    description: 'Silky smooth pâté with real tuna and ocean whitefish.',
    isBestSeller: true,
  },
  {
    id: 'p3',
    name: 'Natural Crunch Treats',
    brand: 'PawVora',
    price: 12.99,
    rating: 5.0,
    reviewCount: 189,
    petCategory: 'dogs',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600&auto=format&fit=crop&q=80',
    badges: ['Heart-Shaped', 'Low Calorie'],
    description: 'Air-dried chicken and sweet potato crunch bites.',
    isNew: true,
  },
  {
    id: 'p4',
    name: 'AquaVitae Fish Oil',
    brand: 'PawVora',
    price: 29.99,
    rating: 4.8,
    reviewCount: 94,
    petCategory: 'cats',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    badges: ['Supplement', 'Omega-3'],
    description: 'Pure Norwegian fish oil drops for coat and joint support.',
    isNew: true,
  },
  {
    id: 'p5',
    name: 'BounceMax Chew Toy',
    brand: 'PawVora Play',
    price: 18.99,
    rating: 4.7,
    reviewCount: 156,
    petCategory: 'dogs',
    productCategory: 'toys',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&auto=format&fit=crop&q=80',
    badges: ['Non-Toxic', 'Durable'],
    description: 'Ultra-durable natural rubber chew toy with treat pocket.',
  },
  {
    id: 'p6',
    name: 'FelineLux Bowl',
    brand: 'PawVora Style',
    price: 24.99,
    rating: 4.9,
    reviewCount: 73,
    petCategory: 'cats',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    badges: ['Eco-Friendly', 'Non-Slip'],
    description: 'Stainless-steel feeding bowl with non-slip silicone base.',
    isNew: true,
  },
  {
    id: 'p7',
    name: 'Dehydrated Beef Bites',
    brand: 'PawVora',
    price: 15.99,
    rating: 4.9,
    reviewCount: 112,
    petCategory: 'dogs',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    badges: ['High Protein', 'Single Ingredient'],
    description: '100% grass-fed dehydrated beef liver bites.',
    isBestSeller: true,
  },
  {
    id: 'p8',
    name: 'Beef Bone Marrow Broth',
    brand: 'PawVora',
    price: 9.99,
    rating: 4.8,
    reviewCount: 64,
    petCategory: 'dogs',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&auto=format&fit=crop&q=80',
    badges: ['Joint Health', 'Collagen Rich'],
    description: 'Slow-simmered organic beef bone broth meal topper.',
  },
  {
    id: 'p9',
    name: 'Salmon Pate Supreme',
    brand: 'PawVora',
    price: 2.99,
    rating: 4.9,
    reviewCount: 88,
    petCategory: 'cats',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=600&auto=format&fit=crop&q=80',
    badges: ['High Moisture', 'Grain-Free'],
    description: 'Gourmet wild salmon recipe pate for adult cats.',
  },
  {
    id: 'p10',
    name: 'Sweet Potato Chips',
    brand: 'PawVora',
    price: 8.99,
    rating: 4.7,
    reviewCount: 145,
    petCategory: 'dogs',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600&auto=format&fit=crop&q=80',
    badges: ['Fiber Rich', 'Low Fat'],
    description: 'Dehydrated sweet potato slices for active chewers.',
  },
  {
    id: 'p11',
    name: 'Hairball Control Paste',
    brand: 'PawVora Wellness',
    price: 14.99,
    rating: 4.6,
    reviewCount: 52,
    petCategory: 'cats',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    badges: ['Digestive Support', 'Vet Formulated'],
    description: 'Natural malt flavored paste to aid hairball passage.',
  },
  {
    id: 'p12',
    name: 'Durable Rope Tug',
    brand: 'PawVora Play',
    price: 11.99,
    rating: 4.9,
    reviewCount: 204,
    petCategory: 'dogs',
    productCategory: 'toys',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&auto=format&fit=crop&q=80',
    badges: ['Teeth Cleaning', 'Heavy Duty'],
    description: '100% natural cotton fiber triple-knot tug rope.',
  },
  {
    id: 'p13',
    name: 'Non-Slip Double Bowl',
    brand: 'PawVora Style',
    price: 32.99,
    rating: 4.8,
    reviewCount: 96,
    petCategory: 'dogs',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    badges: ['Rust Proof', 'Dishwasher Safe'],
    description: 'Dual stainless steel bowls in a silicone stand.',
  },
  {
    id: 'p14',
    name: 'Liver Freeze-Dried Bites',
    brand: 'PawVora',
    price: 18.99,
    rating: 5.0,
    reviewCount: 271,
    petCategory: 'dogs',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    badges: ['Freeze-Dried', 'Single Protein'],
    description: '100% pure beef liver freeze-dried locking in raw nutrients.',
    isBestSeller: true,
  },
  {
    id: 'p15',
    name: 'Turkey Stew Kibble',
    brand: 'PawVora',
    price: 49.99,
    rating: 4.9,
    reviewCount: 182,
    petCategory: 'dogs',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&auto=format&fit=crop&q=80',
    badges: ['High Protein', 'Grain-Free'],
    description: 'Free-run turkey recipe with vegetables and ancient grains.',
  },
  {
    id: 'p16',
    name: 'Chicken Purée Tube Pack',
    brand: 'PawVora',
    price: 6.99,
    rating: 4.9,
    reviewCount: 312,
    petCategory: 'cats',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=600&auto=format&fit=crop&q=80',
    badges: ['Highly Lickable', 'Hydration Booster'],
    description: 'Creamy lickable pureed treats made with farm-raised chicken.',
    isBestSeller: true,
  },
  {
    id: 'p17',
    name: 'Catnip Dental Bites',
    brand: 'PawVora',
    price: 7.99,
    rating: 4.7,
    reviewCount: 99,
    petCategory: 'cats',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600&auto=format&fit=crop&q=80',
    badges: ['Tarter Control', 'Fresh Breath'],
    description: 'Dental crunchy bites stuffed with aromatic premium catnip.',
    isNew: true,
  },
  {
    id: 'p18',
    name: 'Urinary Tract Drops',
    brand: 'PawVora Wellness',
    price: 27.99,
    rating: 4.8,
    reviewCount: 43,
    petCategory: 'cats',
    productCategory: 'food',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    badges: ['Urinary Care', 'Herbal Extracts'],
    description: 'Liquid supplement supporting normal feline kidney and bladder function.',
  },
  {
    id: 'p19',
    name: 'Cat Feather Wand Toy',
    brand: 'PawVora Play',
    price: 9.99,
    rating: 4.9,
    reviewCount: 154,
    petCategory: 'cats',
    productCategory: 'toys',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&auto=format&fit=crop&q=80',
    badges: ['Interactive', 'Natural Feathers'],
    description: 'Retractable wand toy with real feathers and safety bell.',
  },
  {
    id: 'p20',
    name: 'Ceramic Cat Diner',
    brand: 'PawVora Style',
    price: 29.99,
    rating: 4.8,
    reviewCount: 65,
    petCategory: 'cats',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    badges: ['Whisker Friendly', 'Weighted Base'],
    description: 'Shallow ceramic bowls raised to support ergonomic digestion.',
  },
  {
    id: 'p21',
    name: 'Tuna Jerky Strips',
    brand: 'PawVora',
    price: 9.99,
    rating: 4.8,
    reviewCount: 83,
    petCategory: 'cats',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    badges: ['Soft Chews', 'Omega Rich'],
    description: 'Tender tuna jerky fillets sliced into cat bite sizes.',
  },
  {
    id: 'p22',
    name: 'Bounce Tennis Pack',
    brand: 'PawVora Play',
    price: 7.99,
    rating: 4.8,
    reviewCount: 220,
    petCategory: 'dogs',
    productCategory: 'toys',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&auto=format&fit=crop&q=80',
    badges: ['Extra Bouncy', 'Felt Free'],
    description: 'High-visibility natural rubber tennis balls.',
  },
  {
    id: 'p23',
    name: 'Orthopedic Dog Bed',
    brand: 'PawVora Style',
    price: 89.99,
    rating: 4.9,
    reviewCount: 310,
    petCategory: 'dogs',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    badges: ['Memory Foam', 'Washable Cover'],
    description: 'Joint-relieving medical grade orthopedic cushion bed.',
    isBestSeller: true,
  },
  {
    id: 'p24',
    name: 'Chicken Jerky Crunch',
    brand: 'PawVora',
    price: 14.99,
    rating: 4.8,
    reviewCount: 167,
    petCategory: 'dogs',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600&auto=format&fit=crop&q=80',
    badges: ['Grain Free', 'All Natural'],
    description: 'Dehydrated chicken breast strips for high-protein training rewards.',
  },
  {
    id: 'p25',
    name: 'Feline Grooming Comb',
    brand: 'PawVora Style',
    price: 12.99,
    rating: 4.9,
    reviewCount: 184,
    petCategory: 'cats',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    badges: ['Shedding Guard', 'Soft Teeth'],
    description: 'Professional de-shedding slicker brush for long and short cat hair.',
  },
  {
    id: 'p26',
    name: 'Scratching Guard Mats',
    brand: 'PawVora Style',
    price: 19.99,
    rating: 4.7,
    reviewCount: 68,
    petCategory: 'cats',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&auto=format&fit=crop&q=80',
    badges: ['Furniture Saver', 'Self Adhesive'],
    description: 'Clear scratch protection shield sheets for couch corners.',
  },
  {
    id: 'p27',
    name: 'Chicken Jerky Nibblers',
    brand: 'PawVora',
    price: 8.99,
    rating: 4.8,
    reviewCount: 104,
    petCategory: 'cats',
    productCategory: 'treats',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    badges: ['100% Meat', 'Low Calorie'],
    description: 'Freeze dried chicken breast tidbits perfect for cat treat dispensers.',
  },
  {
    id: 'p28',
    name: 'Personalized Leather Collar',
    brand: 'PawVora Style',
    price: 24.99,
    rating: 4.9,
    reviewCount: 122,
    petCategory: 'dogs',
    productCategory: 'accessories',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    badges: ['Full Grain Leather', 'Brass Hardware'],
    description: 'Custom nameplate padded leather collar in classic rose tan.',
    isNew: true,
  },
];
